### ISSUE TITLE
Beta Release Website Connection Issue

### ISSUE THREAD

**Issue by jerryshen2017** [VikramGaru/CSE442-Doves-MessengerApplication-Fall2017#55]
The website occasionally crashes ever since we registered an HTTPS/SSL certificate due to the fact that this project is a NodeJs app. In the future if the website crashes again please let us know and we will run the "nohup node webserver.js &" command on our terminal and the website will start again within seconds. @

**Comment by j3kstrum** [comment]
Hi @jerryshen2017 . I am somewhat confused as to what I should be doing for this issue.

Could you please let me know what I should do?
Thank you!

**Comment by jerryshen2017** [comment]
@j3kstrum    Please check the Ryver messenger. I have given my phone number and please contact me asap.
