### ISSUE TITLE
Take me back to home page does not preserve user

### ISSUE THREAD

**Issue by zsmoore** [VikramGaru/CSE442-Doves-MessengerApplication-Fall2017#80]
If you enter the chat application after signing in and go back to the home page you are logged out and it does not realize you are in a session.

**Comment by jerryshen2017** [comment]
Thanks for pointing out, we implement this feature for security reasons. I am going to leave this issue open for the instructor and the TA.

**Comment by zsmoore** [comment]
Couldn't you use the same logic you use to broadcast message by user to tell the user which person exited?
