### ISSUE TITLE
When user leaves chat room, user called undefined

### ISSUE THREAD

**Issue by zsmoore** [VikramGaru/CSE442-Doves-MessengerApplication-Fall2017#82]
When a user leaves the chat room it displays 'undefined exit chatroom'

**Comment by jerryshen2017** [comment]
@zsmoore  Issue fixed. In the future whenever a user leaves the chatroom there will be a string output "one user exited the chatroom". #85 and #86 fixed.

**Comment by zsmoore** [comment]
Couldn't you use the same logic you use to broadcast message by user to tell the user which person exited?
